// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrIMDC2NXasJQKB8Ux4EB0QEFHTcVOmg',
    appId: '1:496668339725:web:81b67f82ccc6dd7e946f44',
    messagingSenderId: '496668339725',
    projectId: 'expensetracker-de61d',
    authDomain: 'expensetracker-de61d.firebaseapp.com',
    storageBucket: 'expensetracker-de61d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpiTuJDgCpCdfetwP3_SVo1KXGhF182g',
    appId: '1:496668339725:android:acfc61f33575127a946f44',
    messagingSenderId: '496668339725',
    projectId: 'expensetracker-de61d',
    storageBucket: 'expensetracker-de61d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkh-RGFXk0iT4K97RFzEFtqJRmMUN5c0',
    appId: '1:496668339725:ios:758df38a99e51239946f44',
    messagingSenderId: '496668339725',
    projectId: 'expensetracker-de61d',
    storageBucket: 'expensetracker-de61d.appspot.com',
    iosClientId: '496668339725-mmohra54lid4ej71dhbt8ll95pp11hvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkh-RGFXk0iT4K97RFzEFtqJRmMUN5c0',
    appId: '1:496668339725:ios:758df38a99e51239946f44',
    messagingSenderId: '496668339725',
    projectId: 'expensetracker-de61d',
    storageBucket: 'expensetracker-de61d.appspot.com',
    iosClientId: '496668339725-mmohra54lid4ej71dhbt8ll95pp11hvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );
}
